# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c750c17049fb9e3c8ab08849976e4cced14b1a3d5aa016fd32c8d953ed49a2c76d7ad248fe0319179e757bd185c752c5d9b1d39feae895cd0ddb3cbc371c2730

test:
  secret_key_base: 98a13b73767a6e627e1635188e69977c803a10b6542b2c8885f484f4e0119ab37c645e92fd8ac8a59df82280d516513d1475eadaea6824db03d2b1031446671b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
